-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["PalboroughMinesNMs1.png"] = { "Bu'Ghi Howlblade", "Qu'Vho Deathhurler" },
    ["PalboroughMinesNMs2.png"] = { "No'Mho Crimsonarmor", "Zi'Ghi Boneeater", "Be'Hya Hundredwall" },
}
