-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["DavoiNMs.png"] = { "Blubbery Bulge", "Dirtyhanded Gochakzuk", "Hawkeyed Dnatbat", "Poisonhand Gnadgad", "Steelbiter Gudrud", "Tigerbane Bakdak" },
}
