-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["HalvungNMs1.png"] = { "Dorgerwor the Astute", "Farlarder the Shrewd" },
    ["HalvungNMs2.png"] = { "Big Bomb", "Gurfurlur the Menacing", "Kirlirger the Abhorrent", "Mythril Mouth Monamaq" },
}
