-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["TempleofUggalepih4.png"] = { "Crimson-toothed Pawberry" },
    ["TempleofUggalepihNM1.png"] = { "Death from Above", "Flauros", "Sozu Sarberry" },
    ["TempleofUggalepihNM2.png"] = { "Beryl-footed Molberry", "Habetrot", "Manipulator", "Sozu Terberry", "Tonberry Kinq" },
    ["TempleofUggalepihNM3.png"] = { "Bonze Marberry", "Sacrificial Goblet", "Sozu Rogberry" },
}
