-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["Bibiki-bay-Purgonorgo-Isle_nm.png"] = { "Shankha", "Shen", "Serra" },
    ["Bibiki-bay_nm.png"] = { "Intulo", "Splacknuck" },
}
