-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["castle-zvahl-baileys_NM.png"] = { "Duke Haborym", "Grand Duke Batym", "Marquis Allocen", "Marquis Amon" },
    ["castle-zvahl-baileys_NM_2.png"] = { "Likho" },
}
