-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["MeriphataudMountainsNMs.png"] = { "Daggerclaw Dracos", "Patripatan", "Coo Keja the Unseen", "Chonchon spawns amongst the cliffs at (F-9)", "Waraxe Beak", "Naa Zeku the Unwaiting" },
}
