-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["Lufaise-meadows_NM.png"] = { "Amaltheia", "Colorful Leshy", "Defoliate Leshy", "Kurrea", "Megalobugard", "Padfoot", "Flockbock", "Sengann", "Yal-un Eke" },
}
