-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["MazeofShakhramiNM2.png"] = { "Gloombound Lurker", "Trembler Tabitha" },
    ["MazeofShakhramiNMs.png"] = { "Leech King", "Argus", "Lesath", "Aroma Crawler" },
}
