-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["Eldieme-necropolis_1_NM.png"] = { "Skull of Pride" },
    ["Eldieme-necropolis_3_NM.png"] = { "Cwn Cyrff", "Skull of Envy", "Skull of Gluttony", "Skull of Greed", "Skull of Lust", "Skull of Sloth", "Skull of Wrath" },
}
