-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["ArrapagoReefNMs1.png"] = { "Lamie No.8", "Lamia No.19", "Merrow No.5" },
    ["ArrapagoReefNMs2.png"] = { "Lamie No.9", "Medusa" },
    ["Lil_Apkallu_Map.jpg"] = { "Lil' Apkallu" },
}
