-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["Bostaunieux-oubliette_2_NM.png"] = { "Arioch", "Drexerion the Condemned", "Manes", "Phanduron the Condemned", "Sewer Syrup", "Shii" },
    ["Bostaunieux-oubliette_3_NM.png"] = { "Bloodsucker (NM)" },
}
