-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["BhaflauThicketsNMs1.png"] = { "Dea", "Emergent Elm", "Harvestman", "Lividroot Amooshah", "Mahishasura" },
    ["BhaflauThicketsNMs2.png"] = { "Nis Puk" },
}
