-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["YhoatorJungleNM.png"] = { "Bisque-heeled Sunberry", "Bright-handed Kunberry", "Edacious Opo-opo", "Hoar-knuckled Rimberry", "Woodland Sage" },
}
