-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["Uleguerand-range_NM.png"] = { "Bonnacon", "Black Coney", "White Coney", "Snow Maiden", "Mountain Worm", "Frost Flambeau", "Father Frost", "Skvader", "Geush Urvan", "Magnotaur", "Jormungand" },
}
