-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["Mamook3.png"] = { "Gulool Ja Ja" },
    ["MamookNMs1.png"] = { "Devout Radol Ja", "Dragonscaled Bugaal Ja", "Hundredfaced Hapool Ja", "Zizzy Zillah" },
    ["MamookNMs2.png"] = { "Darting Kachaal Ja" },
}
