-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["Beadeaux-NM.png"] = { "Bi'Gho Headtaker", "Da'Dha Hundredmask", "De'Vyu Headhunter", "Ga'Bhu Unvanquished", "Ge'Dha Evileye", "Go'Bhu Gascon", "Zo'Khu Blackcloud" },
}
