-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["Castle-zvahl-keep_NM.png"] = { "Baron Vapula", "Baronet Romwe", "Count Bifrons", "Viscount Morax" },
}
