-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["Fort-ghelsba-NM.png"] = { "Chariotbuster Byakzak", "Hundredscar Hajwaj", "Orcish Panzer", "Kegpaunch Doshgnosh" },
}
