-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["Boyahda-tree_1_NM.png"] = { "Aquarius", "Ellyllon", "Unut" },
    ["Boyahda-tree_3_NM.png"] = { "Ancient Goobbue" },
    ["Boyahda-tree_4_NM.png"] = { "Voluptuous Vivian" },
}
