-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["TahrongiCanyonNMs.png"] = { "Habrok", "Serpopard Ishtar", "Herbage Hunter" },
    ["Tahrongi_Canyon.png"] = { "Yara Ma Yha Who" },
}
