-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["Kuftal-tunnel_1_NM.png"] = { "Cancer" },
    ["Kuftal-tunnel_2_NM.png"] = { "Amemet", "Sabotender Mariachi", "Bloodthirster Madkix", "Guivre" },
    ["Kuftal-tunnel_3_NM.png"] = { "Pelican" },
    ["Kuftal-tunnel_4_NM.png"] = { "Arachne", "Yowie", "Phantom Worm" },
}
