-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["CastleOztrojaNMs1.png"] = { "Moo Ouzi the Swiftblade", "Saa Doyi the Fervid" },
    ["CastleOztrojaNMs3.png"] = { "Yaa Haqa the Profane", "Lii Jixa the Somnolist" },
    ["CastleOztrojaNMs5.png"] = { "Yagudo High Priest", "Yagudo Templar", "Yagudo Avatar", "Tzee Xicu the Manifest" },
    ["CastleOztrojaNMs6.png"] = { "Quu Domi the Gallant" },
    ["CastleOztrojaNMs7.png"] = { "Mee Deggi the Punisher" },
}
