-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["Gustav-tunnel_1_NM.png"] = { "Bune", "Goblinsavior Heronox" },
    ["Gustav-tunnel_2_NM.png"] = { "Amikiri", "Baobhan Sith", "Taxim", "Ungur", "Wyvernpoacher Drachlox" },
}
