-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["Quicksand-caves_1_nm.png"] = { "Antican Praefectus", "Centurio X-I" },
    ["Quicksand-caves_2_nm.png"] = { "Sabotender Bailarin", "Sagittarius X-XIII" },
    ["Quicksand-caves_3_nm.png"] = { "Antican Magister", "Antican Proconsul", "Nussknacker", "Tribunus VII-I" },
    ["Quicksand-caves_4_nm.png"] = { "Triarius X-XV" },
    ["Quicksand-caves_5_nm.png"] = { "Hastatus XI-XII", "Proconsul XII", "Sabotender Bailarina" },
    ["Quicksand-caves_6_nm.png"] = { "Antican Consul", "Antican Legatus", "Antican Praetor" },
    ["Quicksand-caves_7_nm.png"] = { "Antican Tribunus" },
    ["Quicksand-caves_8_nm.png"] = { "Diamond Daig" },
}
