-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["NewtonMovalpolosNMs.png"] = { "Bugbear Matman", "Goblin Collector", "Sword Sorcerer Solisoq", "Swashstox Beadblinker" },
}
