-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["RolanberryFieldsNMs.png"] = { "Black Triple Stars", "Drooling Daisy", "Silk Caterpillar", "Simurgh", "Ravenous Crawler", "Eldritch Edge" },
}
