-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["Batallia-downs_NM.png"] = { "Tottering Toby", "Weeping Willow", "Eyegouger", "Ahtu", "Lumber Jack", "Prankster Maverix", "Skirling Liger" },
}
