-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["SeaSerpentGrottoNM1.png"] = { "Fyuu the Seabellow", "Masan", "Namtar", "Wuur the Sandcomber" },
    ["SeaSerpentGrottoNM2.png"] = { "Qull the Shellbuster", "Seww the Squidlimbed" },
    ["SeaSerpentGrottoNM3.png"] = { "Mouu the Waverider", "Pahh the Gullcaller", "Sea Hog", "Voll the Sharkfinned", "Worr the Clawfisted" },
    ["SeaSerpentGrottoNM4.png"] = { "Charybdis", "Denn the Orcavoiced", "Novv the Whitehearted", "Yarr the Pearleyed", "Zuug the Shoreleaper" },
    ["SeaSerpentGrottoNM5.png"] = { "Abyss Sahagin", "Coral Sahagin", "Ocean Sahagin" },
}
