-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["AydeewaSubterrane2.png"] = { "Chigre", "Nosferatu" },
    ["AydeewaSubterrane3.png"] = { "Bluestreak Gyugyuroon" },
    ["AydeewaSubterrane7.png"] = { "Pandemonium Warden" },
    ["AydeewaSubterraneNMs2.png"] = { "Crystal Eater" },
}
