-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["GarlaigeCitadelNMs2.png"] = { "Hazmat", "Old Two-Wings", "Skewer Sam" },
    ["GarlaigeCitadelNMs3.png"] = { "Frogamander" },
    ["GarlaigeCitadelNMs4.png"] = { "Serket", "Hovering Hotpot" },
}
