-- Auto-generated by maps/download_all_maps.py.
-- Map filename -> list of Notorious Monsters using it.
-- Hand-edit to fix wiki typos (e.g. Leshonki / Voluptuous Vivian).
return {
    ["KorrolokaTunnel1.png"] = { "Morion Worm" },
    ["KorrolokaTunnel2.png"] = { "Morion Worm" },
    ["KorrolokaTunnel3.png"] = { "Morion Worm" },
    ["KorrolokaTunnelNMs1.png"] = { "Falcatus Aranei" },
    ["KorrolokaTunnelNMs2.png"] = { "Cargo Crab Colin" },
    ["KorrolokaTunnelNMs3.png"] = { "Dame Blanche" },
    ["KorrolokaTunnelNMs4.png"] = { "Thoon" },
}
